# Generated by Django 5.1.6 on 2025-03-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_hit',
            field=models.BooleanField(default=False),
        ),
    ]
